apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-api-deployment
  labels:
    app: feedback-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feedback-api
  template:
    metadata:
      labels:
        app: feedback-api
    spec:
      containers:
        - name: feedback-api
          image: product-feedback:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
